apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: wordpress
  namespace: flux-system
spec:
  interval: 1m
  path: ../../apps
  prune: true
  retryInterval: 10s
  dependsOn:
   - name: app-sources  
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: wordpress
  timeout: 3m0s
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app-sources 
  namespace: flux-system
spec:
  interval: 1m
  path: ../../app-sources
  prune: true
  retryInterval: 10s
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 3m0s
  wait: true
